config/routes.rb
Rails.application.routes.draw do
  default_url_options host: ENV.fetch("APPLICATION_HOST")

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope path: '/api/internal' do
    api_version(module: 'Api::Internal::V1', path: { value: 'v1' }, defaults: { format: 'json' }) do
      get 'analytics/customers', to: 'analytics#customers'
      get 'analytics/numbers', to: 'analytics#numbers'
      get 'analytics/subscriptions/:currency', to: 'analytics#subscriptions'
      get 'analytics/mrr_and_arr/:currency', to: 'analytics#mrr_and_arr'
      resources :api_keys, only: [:create, :index, :destroy]
      resources :auth, only: [:create]
      delete 'auth', to: 'auth#destroy'
      post 'sign_up', to: 'auth#sign_up'
      resources :checkouts, param: :token, only: [:show, :update]
      resources :customers, only: [:index, :show, :create, :update, :destroy] do
        resources :payment_methods, only: [:create]
      end
      patch 'invoices/:id/change_status', to: 'invoices#change_status'
      patch 'invoices/:id/mark_as', to: 'invoices#mark_as'
      resources :invoices, only: [:index, :show]
      resources :meters, only: [:index, :show, :update, :create, :destroy]
      resources :organizations, only: [:update]
      resources :payments, only: [:index, :show]
      resources :permissions, only: [:index, :create, :destroy]
      resources :permission_groups, only: [:index, :show, :create, :update, :destroy]
      resources :products, only: [:index, :show, :create, :update, :destroy] do
        resources :pricings, only: [:create, :update, :destroy]
      end
      resources :subscriptions, only: [:create] do
        patch 'edit_trial', to: 'subscriptions#edit_trial'
        patch 'add_pricings', to: 'subscriptions#add_pricings'
        patch 'remove_pricings', to: 'subscriptions#remove_pricings'
        patch 'end_subscription', to: 'subscriptions#end_subscription'
        patch 'end_billing_period', to: 'subscriptions#end_billing_period'
      end
      resources :users, only: [:show]
    end
  end
  scope path: '/api' do
    api_version(module: 'Api::V1', path: { value: 'v1' }, defaults: { format: 'json' }) do
      resources :customers do
        get 'has_permission/:permission_name', to: 'customers#permission'
        get 'permissions', to: 'customers#permissions'
      end
      resources :meter_events, only: [:create]
      resources :invoices, only: [:index, :show]
      patch 'invoices/:id/mark_as', to: 'invoices#mark_as'
      resources :subscriptions, only: [:create] do
        patch 'add_pricings', to: 'subscriptions#add_pricings'
        patch 'remove_pricings', to: 'subscriptions#remove_pricings'
        patch 'end_subscription', to: 'subscriptions#end_subscription'
      end
      get 'widget_settings', to: 'organizations#widget_settings'
      resources :permission_groups, only: [:index]
      resources :products, only: [:index]
    end
  end
  mount Rswag::Api::Engine => '/api-docs'
  mount Rswag::Ui::Engine => '/api-docs'
  devise_for :users, controllers: {
    passwords: 'passwords'
  }
  mount Sidekiq::Web => '/queue'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/admin', to: 'home#admin', as: 'admin_app'
  get 'admin/login_as/:id', to: 'admin#login_as', as: 'admin_login_as'

  get 'widget', to: 'widget#index'
  get 'widget/landing', to: 'widget#landing'
  get 'invoicing', to: 'landings#invoicing', as: 'invoicing'
  post 'send_invoice_email', to: 'landings#send_invoice_email', as: 'send_invoice_email'
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  layout 'landings'

  def invoicing
    Analytics.page(name: 'Invoicing', anonymous_id: request.remote_ip)
  end

  def send_invoice_email
    Analytics.identify(user_id: request.remote_ip, traits: { email: email_param })
    Analytics.track(
      user_id: request.remote_ip,
      event: 'send invoicing demo',
      properties: { email: email_param }
    )
    Analytics.flush

    redirect_to invoicing_path, notice: 'Email Sent   📪'
  end

  private

  def email_param
    @email_param ||= params.require(:email)
  end

  def service
    @service ||= AnalyticsService.new(organization: current_user.organization)
  end
end

app/views/landings/invoicing.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <div class="absolute w-full h-8 text-lg text-center text-black align-middle bg-success">
      <%= msg %>
    </div>
  <% end %>
<% end %>

<div class="h-screen max-h-screen px-6 overflow-hidden bg-white md:px-20">
  <div class="my-6 md:my-8 md:absolute">
    <div class="flex items-center flex-1 h-10 ">
      <a href="#">
        <span class="sr-only">Plutto</span>
         <%= image_tag('logo.png', class: 'h-8') %>
      </a>
    </div>
  </div>
  <div class="flex flex-col items-center justify-center h-full mt-32 md:mt-6">
    <div class="grid content-center h-full grid-cols-1 gap-1 align-middle md:grid-cols-5 md:gap-12">
      <div class="grid content-center grid-cols-1 md:col-span-3">
        <h1 class="text-4xl font-semibold mb-9 text-primary md:text-7xl">
          Create and send subscription invoices on the go.
        </h1>
        <h2 class="text-2xl font-light mb-9 text-secondary">
          Create profesional invoices for your subscription plans, get paid and track payments with plutto.
        </h2>
        <div class="mb-3">
          <%= form_with url: send_invoice_email_path, local: true, method: :post do %>
            <div class="flex">
              <div class="flex-1 min-w-0">
                <%= email_field_tag("email", nil, placeholder: "Enter your email", class: 'block w-full px-4 py-3 text-base text-gray-900 placeholder-gray-500 border-0 rounded-md outline-none bg-gray-100') %>
              </div>
              <div class="mx-2">
                <%= submit_tag "Send Invoice", class: 'block w-full px-4 py-3 font-medium text-black rounded-md shadow bg-melon bg-gradient-to-r from-teal-500 to-cyan-600 hover:from-teal-300 hover:to-cyan-900 hover:bg-melon-600' %>
              </div>
            </div>
          <% end %>
        </div>
        <p class="mb-8 text-base leading-6 text-gray-400 md:mb-0">
          See how it works. Send a Plutto invoice to your email.
        </p>
      </div>
      <div class="pb-10 md:pb-0 md:col-span-2">
        <%= image_tag('invoice.png') %>
      </div>
    </div>
  </div>
</div>